apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
spec:
  ports:
  - name: "80"
    nodePort: 30100
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
  type: NodePort
status:
  loadBalancer: {}
ranjanknagaraju@RANJANs-MacBook-Pro deploy % cat vote-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vote
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vote
    spec:
      containers:
      - image: schoolofdevops/vote:v4
        name: vote
        ports:
        - containerPort: 80
        resources: {}
status: {}
